// <auto-generated />
namespace LojaGaucha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BancoV2Pessoas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BancoV2Pessoas));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191153529_BancoV2Pessoas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
